### ISSUE TITLE
Add PlantUML to Docsify

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#104]
| Task                   | P | EV |
|:-----------------------|:-:|:--:|
| Plant UML to Docsify                  | 3 | 3 |

Enables quick production of UML diagrams by integrating PlantUML to Docsify page

------------------------------------------

## Task List

- [x] Add PlantUML to Docsify
- [x] Add tutorial/examples
- [ ] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* List Acceptance Tests with bullet points

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.
