### ISSUE TITLE
Task 4.1: Add an Expiry date to pictures

### ISSUE THREAD

**Issue by CamilBouzidi** [laurentlaurent/ShutterFeed-a-soen-341-repo#110]
| Task                   | P | EV |
|:-----------------------|:-:|:--:|
| Add Expiry date to pictures                   | 1 | 3 |

If we want users to feel comfortable when posting a picture of their ShutterFeed Stories, we need to ensure that the pictures expire and disappear after a given period (24 hours). Ideally, they would be completely removed from our backend.

------------------------------------------

## Task List
- [ ] Assign Effort Value
- [ ] Assign Priority Number
- [ ] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* A picture stays for no longer than 24 hours and is completely not visible after.

------------------------------------------

## Related features/user stories
This is the first task of our [additional user story about ShutterFeed Stories](#24)

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

**Comment by CamilBouzidi** [comment]
Duplicate of #94
