### ISSUE TITLE
User Story 2: Leave comments on a posted picture

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#13]
| User Story/Task        | P | SP |
|:-----------------------|:-:|:--:|
| Leave comments on a posted picture                  | 2 | 5 |

As a user, I want to be able to comment on a picture to let others know how I feel about the picture. This will send a notification to the user who posted the picture.

------------------------------------------

## Risk

The risk for this user story is:

* Using Angular Material for the UI, which is a new component library for most of us.

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [x] Define tasks
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests [#85]

* User can comment under their own picture
* Find a way to make comment UI scalable
* Have user who posted comment show up under picture
* Set up notification

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by laurent-lao** [comment]
Added long-form in [Wiki page](https://github.com/CamilBouzidi/-REDACTED-a-SOEN-341-Repo/wiki/User-Stories)

**Comment by laurent-lao** [comment]
Updated progress on Issue #3

**Comment by laurent-lao** [comment]
5

**Comment by jmezaber** [comment]
Added the risk for this user story, you know the drill, add more risks if you find any
