### ISSUE TITLE
User Story 3: Follow others

### ISSUE THREAD

**Issue by CamilBouzidi** [laurentlaurent/ShutterFeed-a-soen-341-repo#15]
| User Story        | P | SP |
|:-----------------------|:-:|:--:|
| Follow others                  | High | 8 |

As a user, I would like to keep up with other users' feeds by following their account on the platform. Similarly, I would want other users to be able to follow me on the platform.

------------------------------------------

## Risks

The risk for this user story is:

* Using Firebase to act as our database, same type of risk as user story 1 [#8]

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [x] Define tasks
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests [#91]

* Set up notification
* List of followers/people we follow

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by laurent-lao** [comment]
8

**Comment by jmezaber** [comment]
Added risk, please add/edit risks if you find any

**Comment by CamilBouzidi** [comment]
This issue will be closed with PR #125
