### ISSUE TITLE
User Story 5: Username & Alternate Username generator

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#18]
| User Story        | P | SP |
|:-----------------------|:-:|:--:|
| Username and generator                   | 1 | 8 |

As a user, I would like to pick out a username so that my real name is not always displayed. I would like suggestions for available usernames to pick from when I request one.

------------------------------------------

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [x] Define tasks
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* When signing up, I need to be prompted to choose a username.
* If the user name already exists, I am prompted with another choice that starts with the first letter that I have entered.
* Once my username is selected, it will appear whenever I post or comment.

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by CamilBouzidi** [comment]
Closed with #130
