### ISSUE TITLE
Add Continuous Integration tool to project

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#19]
## Tasks
- [x] Integrate TravisCI to Github @CamilBouzidi 
- [ ] Wait for Code to test
- [ ] Quick test to make sure it works
- [ ] Mark issue as complete

There are multiple options for continuous integration tools that we could use that integrate with Github.

A list of some can be found [here](https://github.com/marketplace?category=continuous-integration)

The slides for the Github tutorial lists those:

- **Travis CI** (Probably the most commonly used)
- Codeship
- CircleCI
- AppVeyor
- Bitrise
- Shippable

**Comment by CamilBouzidi** [comment]
@laurentlaurent I think that we should all pursue TravisCI, especially considering that the professor recommended TravisCI for sprint 2.

**Comment by A-Robitaille** [comment]
Looks like TravisCI needs to be added by someone with owner permissions. I can still figure out how to make it work though

**Comment by CamilBouzidi** [comment]
It seems that there is no use to adding the .travis.yml file, responsible for the build logic unless we already have a proper environment. I will wait for us to have actually have started to code before implementing TravisCI!

**Comment by laurent-lao** [comment]
@CamilBouzidi that makes sense

**Comment by laurent-lao** [comment]
Duplicate of #50
