### ISSUE TITLE
Establish Coding Standard

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#21]
| Task        | P | SP |
|:-----------------------|:-:|:--:|
| Establish Coding Standard                   | 5 | 1 |

Ensure that everyone understands the standards required for developing in a collaborative environment.

------------------------------------------

## Task List

- [x] List languages the project will use
- [x] Research Coding Standard for each languages (Assigned to @jmezaber)
- [x] Discuss Coding Standard
- [x] Enforce Coding Standard in Webstorm
- [ ] Add Article in Wiki @laurentlaurent 

Optional

- [ ] Enforce Coding Standard in VSCode @tommy-josepovic 

------------------------------------------

## Acceptance Tests

* Coding Standard is enforced

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
[Clean Code Concepts adapted for Javascript](https://github.com/ryanmcdermott/clean-code-javascript)
[Google's Code Review Developers Guide](https://google.github.io/eng-practices/review/)
[JavaScript Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#class-definitions)
[JavaScript Style Guide and Coding Conventions](https://www.w3schools.com/js/js_conventions.asp)

**Comment by laurent-lao** [comment]
This [Clean Code Concepts adapted for Javascript](https://github.com/ryanmcdermott/clean-code-javascript) can be a good starting point for a Coding Standard

**Comment by CamilBouzidi** [comment]
Forgive me if this is in the wrong category, but we could definitely add [Google's Code Review Developers Guide](https://google.github.io/eng-practices/review/) to the Coding Standard (or perhaps open another issue dedicated to code reviews)!

**Comment by laurent-lao** [comment]
@CamilBouzidi Definitely a new issue but GREAT IDEA 🙌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by laurent-lao** [comment]
We will either use Js or Typescript and C# @jmezaber

**Comment by jmezaber** [comment]
For C# I found two resources we can reference for coding standards:

- [C# Coding Conventions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#naming-conventions) by Microsoft. It goes in detail on naming, layout and commenting conventions.

- [C# Coding Standards and Naming Conventions](https://www.dofactory.com/reference/csharp-coding-standards). This is some dos and don'ts of C#

For JavaScript I also found two:

- [JavaScript Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#class-definitions) by WordPress. It goes in a lot of details on practically every topic we can think of (from spacing to naming conventions)

- [JavaScript Style Guide and Coding Conventions](https://www.w3schools.com/js/js_conventions.asp) by the good ol' w3schools. Fewer details than the first but covers all the bases.

As for TypeScript I wasn't able to find something very tangible but [this](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple) is the documentation on the base of TypeScript

**Comment by laurent-lao** [comment]
I configured .editorconfig so that a coding style is enforced.
Right now, it has mostly Webstorm settings.

@tommy-josepovic are you using VSCode? If so, could you look into enforcing the style in a similar way as I did? Feel free to remove vscode files from the .gitignore so they can be tracked

**Comment by tjosepo** [comment]
@laurentlaurent I am indeed using VS Code. 

While it doesn't natively support .editorconfig, an extension called **EditorConfig** makes the file work as intended.

Also, with Angular, using the ``ng lint`` command lets you see all styling issues as defined in the file ``tslint.ts``. I think that this command will be used by TravisCI to test our files.

**Comment by laurent-lao** [comment]
@tommy-josepovic 
I think there is a way to add VSCode files to the project so that it auto-installs/auto-activates extensions or even syncs VSCode settings.

I did the Tour of Heroes tutorial through VSCode (and the Getting Started through Webstorm) and I was frustrated by VSCode's inability to auto-import components amongst its other weaknesses.

## In Webstorm

`import { nameOfComponent }` will give suggestion and auto complete with ` from './nameOfComponent.ts'`

Using a component without importing it first will also auto-add it to the import list.

## In VSCode

`import { nameOfComponent }` will only give suggestion (from the Extensions I have anyways).

Not a big deal overall, but just thought I'd point it out.

-------------

@jmezaber since you're uncomfortable with using terminal commands, I'd strongly suggest that you use Webstorm.

`ng generate component nameOfComponent` can easily be done in Webstorm through a `Right-Click -> New... -> Angular Schematics`. Also easier to specify the folder you want to generate the component in and refactor in general.

**Comment by jmezaber** [comment]
Sorry about closing this issue, I clicked the wrong button.

Also, thanks @laurentlaurent for the tip!

**Comment by laurent-lao** [comment]
ng lint restriction is enough
