### ISSUE TITLE
User Story 4 (Additional Feature): ShutterFeed Stories

### ISSUE THREAD

**Issue by CamilBouzidi** [laurentlaurent/ShutterFeed-a-soen-341-repo#24]
| User Story        | P | SP |
|:-----------------------|:-:|:--:|
| ShutterFeed Stories  | High | 9 |

As a user, I would like to be able to upload pictures that would disappear after a time that I et, separately from the main feed of pictures (say, in my Story). That way, I would still be able to update my followers on my day-to-day life without compromising the aesthetic or themes of the feed.

------------------------------------------

## Risks

The fact that this user story deals with time (making the picture disappear after a certain time) is going to add a level of complexity.

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [ ] Define tasks
- [ ] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests [#99]

* Can post a picture 
* Picture will disappear after 24h 

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by jmezaber** [comment]
Updated the acceptance tests, the story point, priority and the risk
