### ISSUE TITLE
Trade study between React vs Angular

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#28]
This has highest priority so we can make a decision asap and get on the user stories.

## Tasks
- [x] Find an Angular tutorial
- [x] Find a React tutorial
- [x] Team members finished [Angular tutorial](https://angular.io/tutorial). React 🚀 when done
- [x] Team members finished [React tutorial](https://reactjs.org/tutorial/tutorial.html). React with 🎉 when done.
- [x] Discuss differences
- [x] Establish choice
- [ ] Add framework to master

**Comment by laurent-lao** [comment]
@A-Robitaille @tommy-josepovic @CamilBouzidi @jmezaber 
Still need to find React tutorial

**Comment by CamilBouzidi** [comment]
This tutorial seems a bit long, but it could be an option:

https://reactjs.org/tutorial/tutorial.html

This one is supposedly 5 minutes, so we could always use it as our test:

https://www.freecodecamp.org/news/learn-react-js-in-5-minutes-526472d292f4/

**Comment by laurent-lao** [comment]
@CamilBouzidi I like the long one! Added to the issue tasks

**Comment by laurent-lao** [comment]
Having completed both tutorials, I think I prefer the way Angular organizes codes between separate .css, .html and .ts code. In React, you would still make a .js file with a child that defines the html code. Meh.

This could also be pointed to as a con for Angular, since the code gets very intricate with the amount of components to juggle. However, since we are all trained in oop, I think it's more or less a moot point.

**Comment by tjosepo** [comment]
I also personally prefer Angular's way of doing thing, I have more experience with Angular, and I really like the [Material library](https://material.angular.io/) for Angular. It's pretty easy to use, and 
I feel like we'll be able to make a very good looking Instagram-like website in no time.

**Comment by laurent-lao** [comment]
@tommy-josepovic React also has a [Material Design Library](https://material-ui.com/). Material is widely used - even JetBrains has Material-based themes (that I use). Just pointing it out hat it's not really a win for Angular or React either way.

JSX in react is meeeeh. Mixing behaviour (script) and content (html) makes me sad. But then again, *ngFor/*ngIf is _technically_ behaviour

**Comment by CamilBouzidi** [comment]
I think that react is awesome and I'd love to work on it, but I have worked with Angular before and I understand that we need to iterate fast. I vote Angular!
