### ISSUE TITLE
Add Docsify to Repo

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#30]
## Tasks
- [x] Add Docsify to repo @CamilBouzidi 
- [x] Wait to find hosting
- [x] Transfer Wiki articles into Docsify @laurentlaurent 
- [x] Test for deadlinks

* Will be marked as done through PR

As per yesterday's meeting, we should move the wiki into a Docsify website.
https://docsify.js.org/#/

**Comment by CamilBouzidi** [comment]
Per #31 , I have added a docsify folder to our repo, where we will host the wiki in order to navigate through it more easily.
