### ISSUE TITLE
Make Zeit host work with Docsify

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#34]
| Task        | P | SP |
|:-----------------------|:-:|:--:|
| Make Zeit host work with Docsify                 | 3 | 0 |

Host the wiki on Zeit

------------------------------------------

## Task List

- [x] Create a Project on Zeit using the repo
- [x] Go to project settings, create a Domain `https://docs-shutterfeed.now.sh/`
- [x] Add a `now.json` file on repo root and add snippet below.
- [x] Create a commit and the domain link should now be attached to the docs (Use the Fix #(number of this issue) syntax in the commit)
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* Wiki is accessible at `https://docs-shutterfeed.now.sh`
* Wiki updates automatically on master pushes (no need for manual serving)

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context

`now.json` file snippet

``` Json
{
  "routes": [
    { "src": "/", "dest": "docs/index.html"},
    { "src": "/(.*)", "dest": "docs/$1" }
  ]
}
```

**Comment by laurent-lao** [comment]
@CamilBouzidi let me know if there are any problems (but it should work as I was able to do it on my side)

**Comment by laurent-lao** [comment]
@CamilBouzidi Any update on this?

---
Just realized I deleted the Fork

Here's the now.json file

```
{
  "routes": [
    { "src": "/", "dest": "docs/index.html"},
    { "src": "/(.*)", "dest": "docs/$1" }
  ]
}
```
