### ISSUE TITLE
Write Requirements from which the features are flown down from

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#37]
| Task        | P | SP |
|:-----------------------|:-:|:--:|
| Write Requirements                   | 4 | 3 |

Write Requirements in the /docs and attach it to the docsify wiki

------------------------------------------

## Task List

- [ ]  List requirements in `/docs`, attach it to the wiki homepage in that folder
- [ ] Write requirements for User Story 1 [#8]
- [ ] Write requirements for User Story 2 [#13]
- [ ] Write requirements for User Story 3 [#15]

------------------------------------------

## Acceptance Tests

* Requirements exist
* Requirements are in the docs

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by CamilBouzidi** [comment]
This issue is no longer valid according to @laurentlaurent
