### ISSUE TITLE
Grading for Sprint 2

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#39]
From [Google Docs](https://docs.google.com/spreadsheets/d/153eB1Gn2Ir85uhrmawp18DOZNIF7FAkl5yfttlXTPIE/edit#gid=0)

- [x] Have issues about user stories
- [x] Continuous integration with test infrastructure ready [#19]
- [x] One core feature finished [#8]
- [x] One core feature almost completed [#13]
- [x] Have task breakdown for each user story [#8] [#13] [#15] [#17] [#18]
- [x] Tasks are assigned to individuals (workload balance)
- [x] Milestone for Sprint 3: have some issues/user stories
* Frequent meetings with meeting minutes available (and document the summary in corresponding github issues)
* Have meaningful commit messages and reference to issue reports
* Have discussion in the repo. Pull requests & review on those requests. (goal: have both pull requests and code review for **all** commits).
