### ISSUE TITLE
Task: Implement Material UI into Angular fork

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#43]
<table>
  <tr>
    <th colspan="3">Implement Material UI</th>
  </tr>
  <tr>
    <td>Acceptance Test</td>
   <td><span title="Priority">P</span></td>
   <td><span title="Story Point">SP</span></td>
  </tr>
  <tr>
    <td>
        <ol>

            <li>Material UI implemeted</li>
        </ol>
    </td>

    <td>2</td>

    <td>8</td>
  </tr>
  <tr>

    <td colspan="3">Implement Material into the Angular to help the front end</td>
  </tr>
</table>

## Task list

<!--~~~~HELPER~~~~~
Use checkboxes like this:
- [ ] Task 1 (Add link to issue number if needed)
- [ ] Task 2 (@ people assigned to the task
~~~~~~~~~~~~~~~~~~~~-->

- [x] Create an Angular branch
- [x] Find tutorials on how to implement it (if needed)
- [x] Implement it

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~~~~~~-->

## Additional context

**Comment by jmezaber** [comment]
Please feel free to add or modify the tasks
