### ISSUE TITLE
Create templates

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#45]
| Task        | P | SP |
|:-----------------------|:-:|:--:|
| Create templates      | 5 | 1 |

For Taxinomy on issue type to make into templates

------------------------------------------

## Task List

Create a template for:

- [x] User Story [#62]
- [x] Task
- [ ] For next meeting/Discussion
- [ ] Requesting help for feature
- [ ] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* Issue templates created

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
The same way we now have a template for user stories, we should have one for these different types of issues. This will create a more homogeneous issue environment.

**Comment by laurent-lao** [comment]
Not sure if we need the rest of the templates
