### ISSUE TITLE
User Account Login

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#47]
| Task        | P | SP |
|:-----------------------|:-:|:--:|
| User Account Login                  | 1 | 3 |

Authentication interface for user so they can access their account.

------------------------------------------

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [x] Update Firebase to accept Auth
- [x] Update Angular to accept Auth
- [ ] Document Auth in `/docs`
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* User can login to their account

------------------------------------------

## Related features/user stories

* From User Story 1 [#8] 
<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.
