### ISSUE TITLE
Integrate Firebase

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#48]
<table>
  <tr>
    <th colspan="3">Integrate Firebase with Angular</th>
  </tr>
  <tr>
    <td>Acceptance Test</td>
   <td><span title="Priority">P</span></td> 
   <td><span title="Story Point">SP</span></td>
  </tr>
  <tr>
    <td>
        <ol>

            <li>Firebase works with Angular</li>
        </ol>
    </td>

    <td>1</td>

    <td>3</td>
  </tr>
  <tr>

    <td colspan="3">Add required files for Angular to work with Firebase</td>
  </tr>
</table>

## Task list

- [x] Define Acceptance test

- [x] Assign Story Point Value

- [x] Assign Priority Number

- [x] Integrate Firebase module with Angular

- [x] Verify issue completion with Acceptance Test. Done!

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~~~~~~-->

* From [#8]

## Additional context
Add any other context or screenshots about the feature request here.
