### ISSUE TITLE
Send pictures to Firebase

### ISSUE THREAD

**Issue by tjosepo** [laurentlaurent/ShutterFeed-a-soen-341-repo#49]
| Task        | P | SP |
|:-----------------------|:-:|:--:|
| Send pictures to Firebase   | 1 | 3 |

This aims to recreate Instagram's basic image sharing feature. This only takes care of the "sharing" part, and does not cover retrieving the image form the database and displaying it properly.

------------------------------------------

## Task List

- [x] A submit button prompts the user for a single file
- [x] A thumbnail image properly appear
- [x] A text input for the caption properly appear
- [x] The "Share" button properly sends the picture, caption and user id to Firebase.
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* When the user is logged in, a button shall appear prompting for an image from the user's device.
* After selecting a file from the user's device, a small preview shall appear on the page which displays the image.
* After selecting a file from the user's device, a small preview shall appear on the page which displays the image, and the user shall be prompted for an optional caption.
* Upon clicking the "Share" button, the picture alongside the caption and user id shall be sent to Firebase.

------------------------------------------

## Related features/user stories

* [#8] User Story 1: Uploading Pictures
* [#47] User Account Login
* [#48] Integrate Firebase

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by laurent-lao** [comment]
Found [this](https://blog.angular.io/file-uploads-come-to-angularfire-6842352b3b47?gi=974b37fee61e) to help
