### ISSUE TITLE
Add TravisCI to repo

### ISSUE THREAD

**Issue by tjosepo** [laurentlaurent/ShutterFeed-a-soen-341-repo#50]
<table>
  <tr>
    <th colspan="3">Add TravisCI to repo</th>
  </tr>
  <tr>
    <td>Acceptance Test</td>
   <td><span title="Priority">P</span></td>
   <td><span title="Story Point">SP</span></td>
  </tr>
  <tr>
    <td>
        <ol>

            <li>TravisCI shall be added to the repo, so that it can automatically build and deploy our master branch to Firebase whenever the branch changes.</li>
        </ol>
    </td>

    <td>1</td>

    <td>3</td>
  </tr>
  <tr>

    <td colspan="3">This is a requirement for sprint 2 mentioned at the end of the Devops powerpoints.</td>
  </tr>
</table>

## Task list

<!--~~~~HELPER~~~~~
Use checkboxes like this:
- [ ] Task 1 (Add link to issue number if needed)
- [ ] Task 2 (@ people assigned to the task
~~~~~~~~~~~~~~~~~~~~-->

- [x] Add TravisCI to repo.
- [x] Configure TravisCI so it can build and deploy the master branch.
- [x] Push errors to the master branch to test if TravisCI will catch them.

## Related features/user stories
* [#48] Integrate Firebase

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by laurent-lao** [comment]
@tommy-josepovic This is a Duplicate of #19 
However, I am marking the other one as duplicate since this one is more complete

**Comment by laurent-lao** [comment]
Closed #19
