### ISSUE TITLE
Create Material UI guide in wiki

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#53]
# Tasks

- [x] Add guide to use Material UI in wiki
- [x] Update `Project-Documentation.md` to link to the guide
- [x] PR with the body indicating Resolve + this issue number

## Related issues
[#43]
