### ISSUE TITLE
Fix User Story template so that tasks are easily clickable

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#62]
| Task | P | SP |
|:-----------------|:-:|:---:|
| Fix User Story template so that tasks are easily clickable  | 5 | 0 |

Checkboxes are currently not clickable when mixing a html table with markdown.

------------------------------------------

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [x] Define tasks
- [ ] Modify template
- [ ] Verify issue completion with Acceptance Test. Done!

## Acceptance Tests

* User Story template has instructions
* Template has clickable checkboxes
* Template works

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.
