### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#63]
| User Story/Task        | P | SP |
|:-----------------------|:-:|:--:|
| Fix Readme.md | 10 | 0 |

Our readme is out of date, it should be fixed.

------------------------------------------

## Task List

- [x] Fix techniques and languages in Readme.md
- [x] Add Github handles next to names (especially since @CamilBouzidi has multiple accounts)
- [x] Links from name should refer to a page where we describe our roles
- [x] Ponder whether we should keep the angular default stuff
- [x] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* Readme is updated with recent information

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by CamilBouzidi** [comment]
Done with #122
