### ISSUE TITLE
Travis continuous delivery

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#65]
| User Story/Task        | P | SP |
|:-----------------------|:-:|:--:|
| Travis continuous delivery | 3 | 3 |

Set Travis .yaml config files so that it auto deploys to Firebase upon build success on master only.

------------------------------------------

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [ ] Research conditional builds
- [ ] Edit travis config file
- [ ] Test with builds on master/other branches
- [ ] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests

* Travis deploys to firebase when master passes checks
* Travis does not deploy to firebase when master does not pass checks
* Travis does not deploy from any other branch than master/develop

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by CamilBouzidi** [comment]
TravisCI can be used to deploy our app on Firebase with every commit. To do so, @laurentlaurent needs:

1. [Firebase Tools and CLI](https://github.com/firebase/firebase-tools#installation)
2. [TravisCI CLI](https://github.com/travis-ci/travis.rb#installation)
3. [To encrypt his firebase token and add it to the .travis.yml file](https://docs.travis-ci.com/user/deployment/firebase/)

**Comment by laurent-lao** [comment]
I have looked into it while I was generating the .yml file 2-3 weeks back but
@CamilBouzidi the problem with this, is that I could not figure out how to set it so that only the `master` branch would auto-deploy via Travis (since Travis .yml file has some weird syntax for per-branch behaviour)

**Comment by laurent-lao** [comment]
due to security concerns of exposing the firebase api, this might not be a good idea. Manual push is a satisfactory deployment strategy
