### ISSUE TITLE
User Story 1: Uploading Pictures

### ISSUE THREAD

**Issue by CamilBouzidi** [laurentlaurent/ShutterFeed-a-soen-341-repo#8]
| User Story        | P | SP |
|:-----------------------|:-:|:--:|
| Uploading Pictures                  | 1 | 13 |

As a user, I want to upload pictures on my account in order to share my life with my friends from a distance. I would not want to be limited in the type of picture that I could upload.

------------------------------------------

## Risk

The risk for this user story is:

* Using Firebase API, which is a relatively new technology for all of us

## Task List

- [x] Define Acceptance test
- [x] Assign Story Point Value
- [x] Assign Priority Number
- [x] Integrate Firebase to Angular [#48] @laurentlaurent 
- [ ] User Account login [#47] @laurentlaurent 
- [ ] User profile page
- [ ] User picture page
- [x] Send pictures to Firebase [#49] @tommy-josepovic 
- [ ] Create a picture feed [#73] @tommy-josepovic   
- [x] Define tasks
- [ ] Verify issue completion with Acceptance Test. Done!

------------------------------------------

## Acceptance Tests [#78]

* User can log in
* User can see their profile
* User can upload jpg, png, (other formats?)
* User cannot upload non-pictures files
* User can see uploaded pictures in their profile

------------------------------------------

## Related features/user stories

<!--~~~~HELPER~~~~~
Use bullet points like this:
* Related feature [#A]
* Related issue number [#B]
~~~~~~~~~~~~~~~-->

## Additional context
Add any other context or screenshots about the feature request here.

**Comment by laurent-lao** [comment]
Added long-form in [Wiki page](https://github.com/CamilBouzidi/-REDACTED-a-SOEN-341-Repo/wiki/User-Stories)

**Comment by laurent-lao** [comment]
Updated progress on Issue #3

**Comment by CamilBouzidi** [comment]
Hello, 

I believe that is our first user story, not our second. See the [Wiki](https://github.com/CamilBouzidi/-REDACTED-a-SOEN-341-Repo/wiki/User-Stories).

**Comment by laurent-lao** [comment]
@CamilBouzidi Sorry, I modified the issue but not the wiki. The account feature should also have a user story (numbered in order of listing from the readme.md)

**Comment by CamilBouzidi** [comment]
@laurentlaurent Hello! I understand why you added having an account as a user story, but @jmezaber , @tommy-josepovic and I were at the tutorial last week and the TA mentioned that having an account and receiving notifications are implicit features in the description of the application and therefore don't count as user stories. Am I misremembering this point?

**Comment by jmezaber** [comment]
Hello guys! Indeed, the TA talked in the last tutorial about the different implicit layers of our user stories. By implicit layers, I mean that they are not really separate features, as in ça va de soi that you need to have an account to use the app and receive notifications. So instead of creating an issue and a separate user story about it, we can mention it in the different user stories. As for the notifications, we can say "this will send a notification to [user1] when [user2] does this" when we write our user stories. Let's not forget also that there are only 3 core features that we need to cover for this sprint: upload, comment, follow.

**Comment by laurent-lao** [comment]
@CamilBouzidi @jmezaber This makes a lot of sense. I'll stand by your decision regarding scrapping Accounts as a user story.

However, I feel that it would be still valid to add it as a user story. User accounts have underlying characteristics such as the ability to edit your name (do we want them to be unable to edit their names, or would they be able to edit it multiple times? time-gated?), upload a picture as their user profile? Plus, we'll gain the ability to reference the issue in a commit and tracking the progress.

So: do you think that Accounts should be a user story, or would the separate features of a User Account be themselves the user stories?

**Comment by CamilBouzidi** [comment]
Hi @laurentlaurent  and @jmezaber,

I personally think that the separate features on the user accounts should be user stories, as it is implied that the user already has an account from which he can upload, follow and comment.

**Comment by laurent-lao** [comment]
13

**Comment by jmezaber** [comment]
Added the risk for this user story, please feel free to add more risks.
